apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bikesharingweb.fullname" . }}
  labels:
    app: {{ template "bikesharingweb.name" . }}
    chart: {{ template "bikesharingweb.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bikesharingweb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bikesharingweb.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
#      initContainers:
#        - env:
#          - name: BASE_NAMESPACES
#            value: dev
#          image: azdsdev/azds-proxy-init:20200325.3
#          imagePullPolicy: IfNotPresent
#          name: devspaces-proxy-init
#          resources: {}
#          securityContext:
#            capabilities:
#              add:
#              - NET_ADMIN
#            runAsUser: 0
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
#          volumeMounts:
#          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#            name: default-token-p5rmk
#            readOnly: true
      containers:
#        - env:
#          - name: NAMESPACE
#            value: azureuser1
#          - name: TRACE_ENDPOINT
#            value: https://azds-59774bcf-bc90-4d76-a0c7-977903b36cee-traces.eus.azdsdev.io/api/v3.2/traces
#          - name: TRACE_VERSION_KEY_HEADER
#            value: x-azds-version-key
#          - name: TRACE_VERSION_KEY
#            value: "0.1"
#          - name: LOG_LEVEL
#            value: "0"
#          - name: AZDS_ENVIRONMENT
#            value: Development
#          image: azdsdev/azds-proxy:20200325.3
#          imagePullPolicy: IfNotPresent
#          name: devspaces-proxy
#          resources: {}
#          securityContext:
#            capabilities:
#              add:
#              - NET_ADMIN
#            runAsUser: 0
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
#          volumeMounts:
#          - mountPath: /etc/kubernetes
#            name: aks-sp
#            readOnly: true
#          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#            name: default-token-p5rmk
#            readOnly: true
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            - name: API_NAME
              value: {{ .Values.apiName | quote }}
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bikesharingweb.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
#      volumes:
#      - name: default-token-p5rmk
#        secret:
#          defaultMode: 420
#          secretName: default-token-p5rmk
#      - hostPath:
#          path: /etc/kubernetes
#          type: ""
#        name: aks-sp
